title: Abdishakur Abdi
email: abdishakurabdi14@gmail.com

url: "https://abdishakurabdi14.github.io"
baseurl: ""

theme: jekyll-theme-cayman

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
